from Human import Human

Test = Human('Name', 80.4, 32, False, 'f1', 'f2', 'f3')
Ksu = Human('Kseniya', 60, 16, False, 'Polya', 'Anya', "Sasha", "Misha")
Kris = Human('Kristina', 41.5, 16, True, 'Amina', "Bogdan", "Tanya")

print(Test)
Test.enumerate_friends()
Test.remove_friend('f1')
Test.enumerate_friends()
Test.remove_friend('not_f')
Test.make_new_friend('new_f')
Test.enumerate_friends()
Test.change_name('Name')
Test.change_name('New_Name')
Test.break_up()
Test.start_relationship()
Test.start_relationship()
Test.break_up()
Test.start_relationship()
Test.grow()
Test.grow()
Test.eat()
Test.eat()
Test.eat_a_lot()
Test.eat_a_lot()
Test.sport()
Test.sport()
print(Test)

print(Ksu)
Ksu.enumerate_friends()
Ksu.remove_friend('Misha')
Ksu.make_new_friend('Kris')
Ksu.change_name('Evgeniya')
Ksu.start_relationship()
Ksu.break_up()
Ksu.grow()
Ksu.eat()
Ksu.eat_a_lot()
Ksu.sport()
print(Ksu)

print(Kris)
Kris.enumerate_friends()
Kris.remove_friend('Sergey')
Kris.make_new_friend('Ksusha')
Kris.change_name('Kristina')
Kris.start_relationship()
Kris.break_up()
Kris.grow()
Kris.eat()
Kris.eat_a_lot()
Kris.sport()
print(Kris)